# Generated by Django 3.0.2 on 2020-05-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audio_prototype', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audios',
            name='audio_id',
            field=models.CharField(default='svalue', max_length=10),
            preserve_default=False,
        ),
    ]
