# Generated by Django 3.0.2 on 2020-05-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audio_prototype', '0002_audios_audio_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audios',
            name='audio_id',
            field=models.CharField(max_length=20),
        ),
    ]
